#!/bin/bash

#########################################################
#
# License: https://github.com/AtaideLab/Targets/blob/main/LICENSE
#
# Author/s: Cali Willet; cali.willet@sydney.edu.au
# Sydney Informatics Hub, The University of Sydney
#
#########################################################

#PBS -P <project>
#PBS -N blast
#PBS -l ncpus=28
#PBS -l mem=252GB
#PBS -l walltime=01:00:00
#PBS -q normalbw
#PBS -W umask=022
#PBS -l wd
#PBS -o ./PBS_logs/blast_IS.o
#PBS -e ./PBS_logs/blast_IS.e
#PBS -l storage=scratch/<project>+gdata/<project>

module load blast+/2.13.0

mkdir -p Output

# formatted BLAST non-redundant nucleotide database
nt=<filepath>/preformatted_2024-02-19/nt

# the prefix name of the multi-fasta  (omit .fasta/.fa suffix) containing all of the IS sequences you want to BLAST 
dataset=IS110_complete 

if [[ $1 == "test" ]]
then
	printf "Running two IS demo\n"
	dataset=IS_2sequence_demo
	nt=nt/IS_Targets_demo_db
	NCPUS=2

	blastn \
        	-db ${nt} \
        	-query ./Input/${dataset}.fasta \
        	-out ./Output/${dataset}.bacterial_archaeal.blast.out \
       	 	-outfmt "6 qseqid qlen length qstart qend sseqid stitle sacc slen sstart send pident mismatch gapopen evalue bitscore"\
        	-num_threads ${NCPUS}

else
	blastn \
		-db ${nt} \
		-taxidlist ./Input/bacterial_archaeal.taxids \
		-query ./Input/${dataset}.fasta \
		-out ./Output/${dataset}.bacterial_archaeal.blast.out \
		-outfmt "6 qseqid qlen length qstart qend sseqid stitle sacc slen sstart send pident mismatch gapopen evalue bitscore"\
		-num_threads ${NCPUS} \
		-mt_mode 1
fi
